/* Automatically generated nanopb constant definitions */
<<<<<<< HEAD
/* Generated by nanopb-0.4.8 */
=======
/* Generated by nanopb-0.4.8-dev */
>>>>>>> main

#include "fd_solcap.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(fd_solcap_FileMeta, fd_solcap_FileMeta, AUTO)


PB_BIND(fd_solcap_BankPreimage, fd_solcap_BankPreimage, AUTO)


PB_BIND(fd_solcap_AccountTableMeta, fd_solcap_AccountTableMeta, AUTO)


PB_BIND(fd_solcap_AccountMeta, fd_solcap_AccountMeta, AUTO)


PB_BIND(fd_solcap_Transaction, fd_solcap_Transaction, AUTO)
<<<<<<< HEAD
=======



>>>>>>> main
